services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ysk_kit
      MYSQL_USER: ysk
      MYSQL_PASSWORD: ysk
    ports:
      - "3306:3306"
    volumes:
      - ysk_kit_mysql:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

volumes:
  ysk_kit_mysql:
