packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

overrides:
  bullmq: "6.3.9"
  react: "19.2.3"
  react-dom: "19.2.3"

allowBuilds:
  argon2: true
  better-sqlite3: true
  electron: true
  esbuild: true
  prisma: true
  "@prisma/engines": true
  "@prisma/client": true
  msgpackr-extract: true

minimumReleaseAgeExclude:
  - "@aws-sdk/client-s3@3.1142.0"
  - "@aws-sdk/s3-request-presigner@3.1142.0"
